# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
# find the sum of the even-valued terms.

max = 4000000
first = 1
second = 2
sum = 0

sequence = [first]

while second < max
	temp = first
	first = second
	second += temp
	sequence << first
end

evens = sequence.select { |n| n % 2 == 0}
sum = evens.inject(0) { |sum, e| sum + e if e % 2 == 0 }

puts sum
# puts evens